// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2zaKvdFEOHX0zeN9teeIzysOrwyGlom8',
    appId: '1:462846058228:web:e1c9c7be7cc86980b088a1',
    messagingSenderId: '462846058228',
    projectId: 'rafiharefa-8396d',
    authDomain: 'rafiharefa-8396d.firebaseapp.com',
    storageBucket: 'rafiharefa-8396d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqu6DQDiZDnLtzzLQnLZ_cGI3DspOmVzE',
    appId: '1:462846058228:android:f896efaae98f2d2fb088a1',
    messagingSenderId: '462846058228',
    projectId: 'rafiharefa-8396d',
    storageBucket: 'rafiharefa-8396d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBd1rWG7IJR1J6eXJmEiT_TisUTZIIGeOc',
    appId: '1:462846058228:ios:093f74afaa027081b088a1',
    messagingSenderId: '462846058228',
    projectId: 'rafiharefa-8396d',
    storageBucket: 'rafiharefa-8396d.appspot.com',
    iosClientId: '462846058228-igousgqhfr0btgirdovqrt3i2pu057is.apps.googleusercontent.com',
    iosBundleId: 'com.example.sistemOperasi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBd1rWG7IJR1J6eXJmEiT_TisUTZIIGeOc',
    appId: '1:462846058228:ios:a0f0e92db3622ccfb088a1',
    messagingSenderId: '462846058228',
    projectId: 'rafiharefa-8396d',
    storageBucket: 'rafiharefa-8396d.appspot.com',
    iosClientId: '462846058228-9bfmine1k7v6633vk84h1t1pnlnb4h56.apps.googleusercontent.com',
    iosBundleId: 'com.example.sistemOperasi.RunnerTests',
  );
}
